// File generated by FlutterFire CLI.
// This is a placeholder - you need to run: flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:1057173770504:web:8d016a62a06b5f43bbdcbd',
    messagingSenderId: '1057173770504',
    projectId: 'roadmobile-81d37',
    authDomain: 'roadmobile-81d37.firebaseapp.com',
    storageBucket: 'roadmobile-81d37.firebasestorage.app',
    measurementId: 'G-B4YSPD99SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
    appId: '1:1057173770504:android:ece9c4f4e1997717bbdcbd',
    messagingSenderId: '1057173770504',
    projectId: 'roadmobile-81d37',
    storageBucket: 'roadmobile-81d37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ',
    appId: '1:1057173770504:ios:9b3e0150e40dddafbbdcbd',
    messagingSenderId: '1057173770504',
    projectId: 'roadmobile-81d37',
    storageBucket: 'roadmobile-81d37.firebasestorage.app',
    iosBundleId: 'com.example.roadmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ',
    appId: '1:1057173770504:ios:9b3e0150e40dddafbbdcbd',
    messagingSenderId: '1057173770504',
    projectId: 'roadmobile-81d37',
    storageBucket: 'roadmobile-81d37.firebasestorage.app',
    iosBundleId: 'com.example.roadmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:1057173770504:web:4c51a3dd17064ca7bbdcbd',
    messagingSenderId: '1057173770504',
    projectId: 'roadmobile-81d37',
    authDomain: 'roadmobile-81d37.firebaseapp.com',
    storageBucket: 'roadmobile-81d37.firebasestorage.app',
    measurementId: 'G-74VQYYSYHR',
  );
}
